name: Testing the action

on: 
  push:

  workflow_dispatch:
    
jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # don't run on PRs
    steps:
      - uses: actions/checkout@v3
      - name: Compile with NPM
        run: | 
          npm ci
          npm run all

  test-load-from-user: # test the action for the user space
    runs-on: ubuntu-latest
    concurrency: single-run
    #if: github.ref == 'refs/heads/main' # don't run on PRs
    steps: 
      - uses: actions/checkout@v3
      # make sure we have a new build, in case the dist folder was not updated
      - name: Compile with NPM
        run: | 
          npm ci
          npm run all

      # run the test
      - uses: ./
        name: Load used actions
        with: 
          PAT: ${{ secrets.PAT }} 
          user: rajbos
        id: load-actions

      - uses: devops-actions/json-to-file@v1.0.1
        with: 
          json: ${{ steps.load-actions.outputs.actions }}
          filename: actions-user.json
        
      - name: Upload result file as artefact
        uses: actions/upload-artifact@v3
        with: 
          name: actions
          path: actions-user.json
  
  test-load-from-organization: # test the action for the organization space
    runs-on: ubuntu-latest
    concurrency: single-run
    #if: github.ref == 'refs/heads/main' # don't run on PRs
    steps: 
      - uses: actions/checkout@v3
      # make sure we have a new build, in case the dist folder was not updated
      - name: Compile with NPM
        run: | 
          npm ci
          npm run all
      # run the test
      - uses: ./
        name: Load used actions
        with: 
          PAT: ${{ secrets.PAT }}
          organization: rajbos-actions
        id: load-actions

      - uses: devops-actions/json-to-file@v1.0.1
        with: 
          json: ${{ steps.load-actions.outputs.actions }}
          filename: actions-organization.json
            
      - name: Upload result file as artefact
        uses: actions/upload-artifact@v3
        with: 
          name: actions-organization
          path: actions-organization.json
